package com.bornparanoid.peakpassthrough.dimension;
import com.google.gson.*;
/** Converts wire coordinates per run, leaving native world state globally authoritative. */
public final class RunSpace {
 private static double number(JsonElement e){if(e==null||!e.isJsonPrimitive()||!e.getAsJsonPrimitive().isNumber())throw new IllegalArgumentException("Coordinate type");double v=e.getAsDouble();if(!Double.isFinite(v))throw new IllegalArgumentException("Coordinate finite");return v;}
 private static void local(double x,double z){if(x< -RunRegions.RADIUS||x>=RunRegions.RADIUS||z< -RunRegions.RADIUS||z>=RunRegions.RADIUS)throw new IllegalArgumentException("Position outside run region");}
 public static JsonObject incoming(RunRegions.Region r,JsonObject original){var o=original.deepCopy();String type=o.get("t").getAsString();switch(type){case "pose"->{if(o.has("x")||o.has("z")){double x=number(o.get("x")),z=number(o.get("z"));local(x,z);o.addProperty("x",x+r.x());o.addProperty("z",z-r.z());}}case "terrain"->{var a=o.getAsJsonArray("origin");if(a==null||a.size()!=3)throw new IllegalArgumentException("Terrain origin");double x=number(a.get(0)),z=number(a.get(2));local(x,z);a.set(0,new JsonPrimitive(x+r.x()));a.set(2,new JsonPrimitive(z-r.z()));}case "loot_spawn"->{var a=o.getAsJsonArray("pos");if(a==null||a.size()!=3)throw new IllegalArgumentException("Loot position");double x=number(a.get(0)),z=number(a.get(2));local(x,z);a.set(0,new JsonPrimitive(x+r.x()));a.set(2,new JsonPrimitive(z-r.z()));}case "env"->{var cells=o.getAsJsonArray("campfires");if(cells==null||cells.size()>16)throw new IllegalArgumentException("Campfires size");for(var token:cells){var a=token.getAsJsonArray();if(a.size()!=3)throw new IllegalArgumentException("Campfire position");double x=number(a.get(0)),z=number(a.get(2));local(x,z);a.set(0,new JsonPrimitive(x+r.x()));a.set(2,new JsonPrimitive(z-r.z()));}}case "spawn_hints"->{var cells=o.getAsJsonArray("cells");if(cells==null||cells.size()>64)throw new IllegalArgumentException("Hints size");for(var token:cells){var a=token.getAsJsonArray();if(a.size()!=5)throw new IllegalArgumentException("Hint cell");double x=number(a.get(0)),z=number(a.get(2));local(x,z);a.set(0,new JsonPrimitive(x+r.x()));a.set(2,new JsonPrimitive(z-r.z()));}}case "action"->{var t=o.getAsJsonObject("target");if(t!=null&&(t.has("x")||t.has("z"))){double x=number(t.get("x")),z=number(t.get("z"));local(x,z);t.addProperty("x",x+r.x());t.addProperty("z",z+r.z());}}default->{}}return o;}
 public static JsonObject outgoing(RunRegions.Region r,JsonObject original){var o=original.deepCopy();String type=o.get("t").getAsString();if(type.equals("boss")){var origin=o.getAsJsonArray("origin");if(origin!=null){if(!r.owns(number(origin.get(0)),number(origin.get(2))))return null;position(r,origin);}}else if(type.equals("chunk")){int cx=o.get("cx").getAsInt(),cz=o.get("cz").getAsInt();if(!r.owns((long)cx*16,(long)cz*16))return null;o.addProperty("cx",cx-r.x()/16);o.addProperty("cz",cz-r.z()/16);if(o.get("terraform") instanceof JsonArray volumes)for(var entry:volumes){var p=entry.getAsJsonObject().getAsJsonArray("origin");p.set(0,new JsonPrimitive(p.get(0).getAsInt()-r.x()));p.set(2,new JsonPrimitive(p.get(2).getAsInt()-r.z()));}}else if(type.equals("block")||type.equals("break_progress")){double x=number(o.get("x")),z=number(o.get("z"));if(!r.owns(x,z))return null;o.addProperty("x",(int)x-r.x());o.addProperty("z",(int)z-r.z());}else if(type.equals("debug_state")){o.addProperty("x",number(o.get("x"))-r.x());o.addProperty("z",number(o.get("z"))-r.z());}else if(type.equals("entity_update")||type.equals("sound")||type.equals("teleport")){var p=o.getAsJsonArray("pos");if(p!=null){if(!r.owns(number(p.get(0)),number(p.get(2))))return null;position(r,p);}var pose=o.getAsJsonObject("pose");if(pose!=null&&pose.get("ownerPos") instanceof JsonArray owner)position(r,owner);}return o;}
 private static void position(RunRegions.Region r,JsonArray p){p.set(0,new JsonPrimitive(number(p.get(0))-r.x()));p.set(2,new JsonPrimitive(number(p.get(2))-r.z()));}
}
