<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Peakthrough</AssemblyName>
    <RootNamespace>PeakCreativeMode.Plugin</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PeakCreativeMode.Core/PeakCreativeMode.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(BepInExCore)/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(BepInExCore)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Sirenix.Serialization"><HintPath>$(PeakManaged)/Sirenix.Serialization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(PeakManaged)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(PeakManaged)/Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.InputSystem"><HintPath>$(PeakManaged)/Unity.InputSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Zorro.Core.Runtime"><HintPath>$(PeakManaged)/Zorro.Core.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule"><HintPath>$(PeakManaged)/UnityEngine.UnityWebRequestAudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule"><HintPath>$(PeakManaged)/UnityEngine.UnityWebRequestModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AudioModule"><HintPath>$(PeakManaged)/UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(PeakManaged)/UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(PeakManaged)/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(PeakManaged)/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(PeakManaged)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(PeakManaged)/UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(PeakManaged)/UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(PeakManaged)/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Photon3Unity3D"><HintPath>$(PeakManaged)/Photon3Unity3D.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="PhotonRealtime"><HintPath>$(PeakManaged)/PhotonRealtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="PhotonUnityNetworking"><HintPath>$(PeakManaged)/PhotonUnityNetworking.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
