package com.bornparanoid.peakpassthrough.session;
import com.bornparanoid.peakpassthrough.blocks.BlockWorld;
import com.bornparanoid.peakpassthrough.bridge.BridgeServer;
import com.bornparanoid.peakpassthrough.inventory.InventoryMessages;
import com.google.gson.*;
import java.util.*;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.projectile.arrow.AbstractArrow;
import net.minecraft.world.entity.projectile.FishingHook;
import net.minecraft.world.entity.projectile.throwableitemprojectile.ThrowableItemProjectile;
/** Active-radius entity snapshots with authoritative native poses and reconnect adds. */
public final class EntityFeed {
 private final BlockWorld blocks;private final BridgeServer bridge;private final Map<Integer,Set<Integer>> seen=new HashMap<>();
 private final Map<Integer,double[]> motion=new HashMap<>();private long tick;
 public EntityFeed(BlockWorld blocks,BridgeServer bridge){this.blocks=blocks;this.bridge=bridge;}
 private boolean near(Entity e,ServerPlayer p){double dx=e.getX()-p.getX(),dz=e.getZ()-p.getZ();int range=e instanceof EnderDragon?160:52;return dx*dx+dz*dz<=range*range&&Math.abs(e.getY()-p.getY())<=96;}
 private boolean eligible(Entity e){return !e.isRemoved()&&(e instanceof net.minecraft.world.entity.item.PrimedTnt||e instanceof ItemEntity||e instanceof Mob||e instanceof AbstractArrow||e instanceof FishingHook||e instanceof ThrowableItemProjectile||e instanceof net.minecraft.world.entity.projectile.hurtingprojectile.DragonFireball||e instanceof net.minecraft.world.entity.AreaEffectCloud cloud&&cloud.getOwner() instanceof EnderDragon);}
 public void tick(Map<Integer,? extends ServerPlayer> clients){var entities=new ArrayList<Entity>();for(var e:blocks.level().getAllEntities())if(eligible(e)){entities.add(e);var last=motion.computeIfAbsent(e.getId(),id->new double[]{e.getX(),e.getZ(),0,0});double step=Math.hypot(e.getX()-last[0],e.getZ()-last[1]);last[0]=e.getX();last[1]=e.getZ();last[2]+=step*4;last[3]=Math.min(1,step*4);if(e instanceof Mob mob&&!(e instanceof EnderDragon dragon&&com.bornparanoid.peakpassthrough.boss.DragonArena.isArena(dragon))){boolean active=clients.values().stream().anyMatch(p->!p.isSpectator()&&near(e,p));mob.setNoAi(!active);}}
  motion.keySet().retainAll(entities.stream().map(Entity::getId).collect(java.util.stream.Collectors.toSet()));
  tick++;var updates=new HashMap<Integer,String>();
  for(var entry:clients.entrySet()){int client=entry.getKey();var current=new HashSet<Integer>();var old=seen.computeIfAbsent(client,id->new HashSet<>());for(var e:entities){if(entry.getValue().isSpectator()||!near(e,entry.getValue()))continue;current.add(e.getId());boolean first=old.add(e.getId());if(first){var o=new JsonObject();o.addProperty("t","entity_add");o.addProperty("id",e.getId());o.addProperty("type",BuiltInRegistries.ENTITY_TYPE.getKey(e.getType()).toString());if(e instanceof EnderDragon)o.addProperty("uuid",e.getUUID().toString());if(e instanceof ItemEntity item)o.add("item",InventoryMessages.stack(item.getItem()));else if(e instanceof ThrowableItemProjectile projectile){o.add("item",InventoryMessages.stack(projectile.getItem()));o.addProperty("projectile",true);}var size=new JsonArray();size.add(e.getBbWidth());size.add(e.getBbHeight());o.add("size",size);bridge.send(client,o.toString());}if(EntityFeedPolicy.update(tick,first))bridge.send(client,updates.computeIfAbsent(e.getId(),id->update(e)));}for(int id:new HashSet<>(old))if(!current.contains(id)){var o=new JsonObject();o.addProperty("t","entity_remove");o.addProperty("id",id);bridge.send(client,o.toString());old.remove(id);}}
 }
 private String update(Entity e){var o=new JsonObject();o.addProperty("t","entity_update");o.addProperty("id",e.getId());var p=new JsonArray();p.add(e.getX());p.add(e.getY());p.add(e.getZ());o.add("pos",p);var rot=new JsonObject();rot.addProperty("bodyYaw",e instanceof LivingEntity living?living.yBodyRot:e.getYRot());rot.addProperty("headYaw",e instanceof LivingEntity living?living.yHeadRot:e.getYRot());rot.addProperty("pitch",e.getXRot());o.add("rot",rot);var pose=new JsonObject();if(e instanceof net.minecraft.world.entity.item.PrimedTnt tnt)pose.addProperty("fuse",tnt.getFuse());if(e instanceof net.minecraft.world.entity.AreaEffectCloud cloud)pose.addProperty("radius",cloud.getRadius());if(e instanceof Mob)pose.addProperty("grounded",e.onGround());if(e instanceof LivingEntity living){pose.addProperty("limbSwing",(float)motion.get(e.getId())[2]);pose.addProperty("limbAmount",(float)motion.get(e.getId())[3]);pose.addProperty("health",living.getHealth());if(e instanceof Mob){var held=InventoryMessages.stack(living.getMainHandItem());held.addProperty("using",living.isUsingItem());pose.add("held",held);}}if(e instanceof EnderDragon dragon){pose.addProperty("flap",dragon.flapTime);pose.addProperty("phase",dragon.getPhaseManager().getCurrentPhase().getPhase().getId());pose.addProperty("deathTime",dragon.dragonDeathTime);var parts=new JsonArray();String[] names={"head","neck","body","tail1","tail2","tail3","wing1","wing2"};var nativeParts=dragon.getSubEntities();for(int i=0;i<nativeParts.length;i++){var part=nativeParts[i];var row=new JsonObject();row.addProperty("part",names[i]);var offset=new JsonArray();offset.add(part.getX()-e.getX());offset.add(part.getY()-e.getY());offset.add(part.getZ()-e.getZ());row.add("offset",offset);var size=new JsonArray();size.add(part.getBbWidth());size.add(part.getBbHeight());row.add("size",size);parts.add(row);}pose.add("parts",parts);}if(e instanceof FishingHook hook&&hook.getPlayerOwner()!=null){var owner=hook.getPlayerOwner();pose.addProperty("owner",owner.getGameProfile().id().toString());var ownerPos=new JsonArray();ownerPos.add(owner.getX());ownerPos.add(owner.getY()+1.2);ownerPos.add(owner.getZ());pose.add("ownerPos",ownerPos);pose.addProperty("biting",((com.bornparanoid.peakpassthrough.mixin.FishingHookAccessor)hook).peak$isBiting());}o.add("pose",pose);if(e instanceof ItemEntity item)o.add("item",InventoryMessages.stack(item.getItem()));else if(e instanceof ThrowableItemProjectile projectile){o.add("item",InventoryMessages.stack(projectile.getItem()));o.addProperty("projectile",true);}return o.toString();}
 public void remove(int client){seen.remove(client);}
}
