package com.bornparanoid.peakpassthrough.boss;
import com.google.gson.*;
import com.bornparanoid.peakpassthrough.blocks.BlockWorld;
import com.bornparanoid.peakpassthrough.bridge.BridgeServer;
import com.bornparanoid.peakpassthrough.dimension.RunRegions;
import com.bornparanoid.peakpassthrough.world.*;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.enderdragon.phases.EnderDragonPhase;
import net.minecraft.world.phys.Vec3;
import java.util.*;
import java.io.IOException;
/** Native dragon lifecycle. Durable identity precedes spawn; damaged records never reset. */
public final class DragonArena {
 public static final String TAG="peak_arena",ORBIT_TAG="peak_orbit_";
 public record Peer(int client,String seed,RunRegions.Region region,ServerPlayer player){}
 public record Bounds(BlockPos origin,int orbit){}
 private static final org.slf4j.Logger LOG=org.slf4j.LoggerFactory.getLogger("passpeakthrough/dragon");
 private static final class Run {DragonState state;DragonConfig config=DragonConfig.parse(null);BlockPos expected;EnderDragon dragon;long loadedAt,retryAt;boolean missingWarned,finished;}
 private final BlockWorld blocks;private final BridgeServer bridge;private final RunEvents events;private final Map<String,Run> runs=new HashMap<>();private final Set<String> refused=new HashSet<>();private long ticks;
 public DragonArena(BlockWorld blocks,BridgeServer bridge,RunEvents events){this.blocks=blocks;this.bridge=bridge;this.events=events;}
 public static boolean isArena(EnderDragon dragon){return dragon.entityTags().contains(TAG);}
 public static int orbit(EnderDragon dragon){for(String tag:dragon.entityTags())if(tag.startsWith(ORBIT_TAG))try{int n=Integer.parseInt(tag.substring(ORBIT_TAG.length()));if(n>=20&&n<=160)return n;}catch(NumberFormatException ignored){}return 60;}
 private Run run(String seed)throws IOException{if(refused.contains(seed))throw new IOException("Dragon state refused");var old=runs.get(seed);if(old!=null)return old;var r=new Run();r.loadedAt=ticks;try{String stored=events.dragonState(seed);if(stored.equals("not_started"))r.state=new DragonState();else{var raw=JsonParser.parseString(stored).getAsJsonObject();r.state=DragonState.parse(raw);r.config=DragonConfig.parse(raw.has("config")?raw.getAsJsonObject("config"):null);}}catch(RuntimeException e){refused.add(seed);LOG.error("Invalid persisted dragon state for {}; refusing reset",seed,e);throw new IOException("Invalid persisted dragon state; refusing reset",e);}runs.put(seed,r);return r;}
 private void persist(String seed,Run r)throws IOException{persist(seed,r,r.state);}
 private void persist(String seed,Run r,DragonState state)throws IOException{var raw=state.json();var config=new JsonObject();config.addProperty("triggerSegment",r.config.triggerSegment());config.addProperty("maxHealth",r.config.maxHealth());config.addProperty("orbit",r.config.orbit());raw.add("config",config);events.dragonState(seed,raw.toString());}
 public void receive(String seed,RunRegions.Region region,ServerPlayer player,JsonObject o)throws IOException{if(!o.has("kind")||!o.get("kind").isJsonPrimitive())return;var r=run(seed);String kind=o.get("kind").getAsString();if(kind.equals("run_start")){var beach=WorldEvents.position(o.get("beach"),region);if(beach==null||player.distanceToSqr(beach)>256)return;if(!r.state.triggered())r.config=DragonConfig.parse(o.has("dragon")?o.getAsJsonObject("dragon"):null);var fires=o.has("campfires")?o.getAsJsonArray("campfires"):null;if(fires==null||fires.size()>16)return;for(var entry:fires){var fire=entry.getAsJsonObject();if(BowPlacement.segment(fire.get("segment"))==r.config.triggerSegment()){var pos=WorldEvents.position(fire.get("pos"),region);if(pos!=null)r.expected=BlockPos.containing(pos);}}return;}
  if(!kind.equals("campfire_lit")||BowPlacement.segment(o.get("segment"))!=r.config.triggerSegment()||r.state.triggered()||r.state.killed())return;var pos=WorldEvents.position(o.get("pos"),region);if(pos==null||player.distanceToSqr(pos)>64*64||r.expected==null||Vec3.atCenterOf(r.expected).distanceToSqr(pos)>16||!region.owns(pos.x-192,pos.z-192)||!region.owns(pos.x+192,pos.z+192))return;
  var dragon=EntityTypes.ENDER_DRAGON.create(blocks.level(),EntitySpawnReason.TRIGGERED);if(dragon==null)throw new IOException("Native dragon could not be created");if(!r.state.trigger(BlockPos.containing(pos)))return;persist(seed,r);dragon.setUUID(r.state.uuid());dragon.setFightOrigin(r.state.origin());dragon.addTag(TAG);dragon.addTag(ORBIT_TAG+r.config.orbit());dragon.getAttribute(Attributes.MAX_HEALTH).setBaseValue(r.config.maxHealth());dragon.setHealth(dragon.getMaxHealth());dragon.setPos(pos.x,pos.y+40,pos.z-r.config.orbit());dragon.getPhaseManager().setPhase(EnderDragonPhase.HOLDING_PATTERN);if(!blocks.level().addFreshEntity(dragon))throw new IOException("Native dragon identity already present; refusing another spawn");r.dragon=dragon;LOG.info("Triggered dragon {} for {} at {} health {} orbit {}",dragon.getUUID(),seed,r.state.origin(),r.config.maxHealth(),r.config.orbit());
 }
 public List<Bounds> bounds(){var result=new ArrayList<Bounds>();for(var r:runs.values())if(r.state.triggered()&&!r.state.killed())result.add(new Bounds(r.state.origin(),r.config.orbit()));return List.copyOf(result);}
 public void tick(List<Peer> peers,long tick){ticks=tick;for(var peer:peers)try{run(peer.seed());}catch(IOException e){if(refused.add(peer.seed()))LOG.error("Cannot restore dragon {}: {}",peer.seed(),e.getMessage());}for(var entry:runs.entrySet()){String seed=entry.getKey();var r=entry.getValue();if(!r.state.triggered())continue;if(r.state.killed()){finish(seed,r,peers);continue;}if(r.dragon==null){var entity=blocks.level().getEntity(r.state.uuid());if(entity instanceof EnderDragon d){r.dragon=d;if(!d.getFightOrigin().equals(r.state.origin())){d.setFightOrigin(r.state.origin());d.setDeltaMovement(Vec3.ZERO);d.getPhaseManager().setPhase(EnderDragonPhase.HOLDING_PATTERN);d.getPhaseManager().getCurrentPhase().begin();}}else{if(tick-r.loadedAt>200&&!r.missingWarned){r.missingWarned=true;LOG.warn("Persisted dragon {} is not loaded; keeping its identity and refusing duplicate",r.state.uuid());}continue;}}
   var dragon=r.dragon;boolean active=peers.stream().anyMatch(p->p.seed().equals(seed)&&!p.player().isSpectator()&&p.player().distanceToSqr(Vec3.atCenterOf(r.state.origin()))<=200*200);dragon.setNoAi(!active);
   if(dragon.getRemovalReason()==Entity.RemovalReason.KILLED||dragon.dragonDeathTime>=199){if(tick<r.retryAt)continue;try{r.state=DragonVictory.persist(r.state,state->persist(seed,r,state));finish(seed,r,peers);LOG.info("Dragon {} killed; durable no-respawn state saved",r.state.uuid());}catch(IOException e){r.retryAt=tick+100;LOG.error("Cannot persist dragon victory; retaining arena for retry",e);}continue;}
   if(tick%5==0){var boss=new JsonObject();boss.addProperty("t","boss");boss.addProperty("id",r.state.uuid().toString());boss.addProperty("name","Ender Dragon");boss.addProperty("progress",Math.max(0,Math.min(1,dragon.getHealth()/dragon.getMaxHealth())));var origin=new JsonArray();origin.add(r.state.origin().getX());origin.add(r.state.origin().getY());origin.add(r.state.origin().getZ());boss.add("origin",origin);boss.addProperty("orbit",r.config.orbit());for(var peer:peers)if(peer.seed().equals(seed)&&!peer.player().isSpectator()&&peer.player().distanceToSqr(Vec3.atCenterOf(r.state.origin()))<=160*160)bridge.send(peer.client(),boss.toString());}
  }}
 private void finish(String seed,Run r,List<Peer> peers){if(r.finished||ticks<r.retryAt)return;try{var origin=r.state.origin();boolean reward=events.claimLoot(seed,"dragon-egg:"+r.state.uuid());if(reward){var egg=new net.minecraft.world.entity.item.ItemEntity(blocks.level(),origin.getX()+.5,origin.getY()+1.2,origin.getZ()+.5,new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.DRAGON_EGG));egg.setUnlimitedLifetime();egg.setNoGravity(true);egg.setDeltaMovement(Vec3.ZERO);egg.setDefaultPickUpDelay();blocks.level().addFreshEntity(egg);com.bornparanoid.peakpassthrough.sound.SoundFeed.emit(blocks.level(),origin.getX(),origin.getY(),origin.getZ(),net.minecraft.sounds.SoundEvents.UI_TOAST_CHALLENGE_COMPLETE,4,1);com.bornparanoid.peakpassthrough.sound.SoundFeed.emit(blocks.level(),origin.getX(),origin.getY(),origin.getZ(),net.minecraft.sounds.SoundEvents.ENDER_DRAGON_DEATH,4,1);}var message=new JsonObject();message.addProperty("t","boss_remove");message.addProperty("id",r.state.uuid().toString());message.addProperty("killed",true);for(var peer:peers)if(peer.seed().equals(seed))bridge.send(peer.client(),message.toString());r.finished=true;}catch(IOException e){r.retryAt=ticks+100;LOG.error("Cannot persist dragon reward; retrying without respawn",e);}}
}
